name: amped_media_admin
description: "AMPED Media"

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  responsive_builder: ^0.7.0
  get_it: ^7.7.0
  provider: ^6.1.2
  http: ^1.2.1
  intl: ^0.19.0
  flutter_bloc: ^8.1.5
  fpdart: ^1.1.0
  go_router: ^14.1.1
  flutter_gen: ^5.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
